db:
  host: localhost
  port: 3306
  username: root
  password: Ddyyll0526
  database: galaxy
  parameters: # charset=utf8mb4&parseTime=True&loc=Local"
    charset: utf8mb4
    parseTime: true
    loc: Local