name: Docker Build and Push

on:
  push:
    branches:
      - dev

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - context: "master"
            tag: "master-latest"
            dockerfile: "master/Dockerfile"
            platform: "linux/amd64,linux/arm64"
          - context: "node"
            tag: "node-latest"
            dockerfile: "node/Dockerfile"
            platform: "linux/amd64,linux/arm64"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Debug matrix values
        run: |
          echo "Context: ${{ matrix.context }}"
          echo "Tag: ${{ matrix.tag }}"
          echo "Dockerfile: ${{ matrix.dockerfile }}"
          echo "Platform: ${{ matrix.platform }}"

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./${{ matrix.context }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/galaxyweb:${{ matrix.tag }}
          file: ./${{ matrix.dockerfile }}
          platforms: ${{ matrix.platform }}
