name: Docker Build and Push

on:
  push:
    branches:
      - dev
  workflow_dispatch: # 允许手动触发

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dockerfile:
          - path: "Dockerfile"
            tag: "master-latest"
            context: "master"
          - path: "Dockerfile"
            tag: "node-latest"
            context: "node"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.context }}  # 使用矩阵变量中的 context
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/galaxyweb:${{ matrix.tag }}
          file: ${{ matrix.path }}
